const level1 = new Level(
    [
        /* new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(),
        new Enemy(), */
        new Endboss()
    ],
    [
        new Sun(),
        new Cloud(1000),
        new Cloud(2000),
        new Cloud(3000),
        new Tumble(800),
        new Tumble(3000),
        new Tumble(5000),
        new Tumble(7800)
    ],
    [
        new Bottle(850),
        new Bottle(950),
        new Bottle(1050),
        new Bottle(2000),
        new Bottle(2100),
        new Bottle(2200),
        new Bottle(3500),
        new Bottle(3600),
        new Bottle(3700),
        new Bottle(4500),
        new Bottle(4600),
        new Bottle(4700)
    ],
    [
        new Coin(500, 250),
        new Coin(600, 300),
        new Coin(700, 250),
        new Coin(1500, 280),
        new Coin(1600, 330),
        new Coin(1700, 280),
        new Coin(2500, 250),
        new Coin(2600, 300),
        new Coin(2700, 250),
        new Coin(3100, 280),
        new Coin(3200, 330),
        new Coin(3300, 280)
    ],
    [
        new Ground('img/5_background/layers/air.png', -719),
        new Ground('img/5_background/layers/3_third_layer/1.png', -719),
        new Ground('img/5_background/layers/2_second_layer/1.png', -719),
        new Ground('img/5_background/layers/1_first_layer/1.png', -719),
        new Ground('img/5_background/layers/air.png', 0),
        new Ground('img/5_background/layers/3_third_layer/2.png', 0),
        new Ground('img/5_background/layers/2_second_layer/2.png', 0),
        new Ground('img/5_background/layers/1_first_layer/2.png', 0),
        new Ground('img/5_background/layers/air.png', 719),
        new Ground('img/5_background/layers/3_third_layer/1.png', 719),
        new Ground('img/5_background/layers/2_second_layer/1.png', 719),
        new Ground('img/5_background/layers/1_first_layer/1.png', 719),
        new Ground('img/5_background/layers/air.png', 719 * 2),
        new Ground('img/5_background/layers/3_third_layer/2.png', 719 * 2),
        new Ground('img/5_background/layers/2_second_layer/2.png', 719 * 2),
        new Ground('img/5_background/layers/1_first_layer/2.png', 719 * 2),
        new Ground('img/5_background/layers/air.png', 719 * 3),
        new Ground('img/5_background/layers/3_third_layer/1.png', 719 * 3),
        new Ground('img/5_background/layers/2_second_layer/1.png', 719 * 3),
        new Ground('img/5_background/layers/1_first_layer/1.png', 719 * 3),
        new Ground('img/5_background/layers/air.png', 719 * 4),
        new Ground('img/5_background/layers/3_third_layer/2.png', 719 * 4),
        new Ground('img/5_background/layers/2_second_layer/2.png', 719 * 4),
        new Ground('img/5_background/layers/1_first_layer/2.png', 719 * 4),
        new Ground('img/5_background/layers/air.png', 719 * 5),
        new Ground('img/5_background/layers/3_third_layer/1.png', 719 * 5),
        new Ground('img/5_background/layers/2_second_layer/1.png', 719 * 5),
        new Ground('img/5_background/layers/1_first_layer/1.png', 719 * 5),
        new Ground('img/5_background/layers/air.png', 719 * 6),
        new Ground('img/5_background/layers/3_third_layer/2.png', 719 * 6),
        new Ground('img/5_background/layers/2_second_layer/2.png', 719 * 6),
        new Ground('img/5_background/layers/1_first_layer/2.png', 719 * 6),
        new Ground('img/5_background/layers/air.png', 719 * 7),
        new Ground('img/5_background/layers/3_third_layer/1.png', 719 * 7),
        new Ground('img/5_background/layers/2_second_layer/1.png', 719 * 7),
        new Ground('img/5_background/layers/1_first_layer/1.png', 719 * 7),
        new Ground('img/5_background/layers/air.png', 719 * 8),
        new Ground('img/5_background/layers/3_third_layer/2.png', 719 * 8),
        new Ground('img/5_background/layers/2_second_layer/2.png', 719 * 8),
        new Ground('img/5_background/layers/1_first_layer/2.png', 719 * 8),
        new Ground('img/5_background/layers/air.png', 719 * 9),
        new Ground('img/5_background/layers/3_third_layer/1.png', 719 * 9),
        new Ground('img/5_background/layers/2_second_layer/1.png', 719 * 9),
        new Ground('img/5_background/layers/1_first_layer/1.png', 719 * 9)
    ]
);